CREATE TABLE wodzone.wod_details (
  id_wod_detail INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name varchar,
  last_name varchar,
  email varchar,
  birth_date timestamp,
  telephone varchar,
  password varchar,
  id_role int,
  tee_shirt int,
  short int,
  pointure int,
  created_at timestamp,
  updated_at timestamp
);

CREATE TABLE wodzone.tailles (
  "id_taille" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "value" varchar(10)
);

CREATE TABLE wodzone.history_team_changes (
  "id_history_team_change" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_participant" int,
  "id_user_remplacant" int,
  "id_user_remplace" int,
  "created_at" timestamp
);



ALTER TABLE wodzone.wod_score_details ADD FOREIGN KEY (id_wod) REFERENCES wodzone.wods (id_wod);
ALTER TABLE wodzone.score_details ADD FOREIGN KEY (id_score) REFERENCES wodzone.scores (id_score);
ALTER TABLE wodzone.score_details ADD FOREIGN KEY (id_wod_score_details) REFERENCES wodzone.wod_score_details (id_wod_score_details);
INSERT INTO wod_types ("name", compared, suffix) VALUES('NOMBRE', 'descending', 'nb');

--Donne une liste de toutes les contraintes définies sur la table
SELECT conname FROM pg_constraint WHERE conrelid = 'athletes'::regclass;

-- POUR INITAILISER LA VALEUR DE L'ID EN FONCTION DU DERNIER INSERT (PERMET D'EVITER LES ERREURS DE DUPLICATES)
-- Étape 1 : Trouver la valeur maximale actuelle de l'ID primaire
SELECT MAX(id) FROM ma_table;

-- Voici la commande pour réinitialiser la séquence :
ALTER SEQUENCE nom_de_sequence RESTART WITH valeur_max_a  ctuelle + 1;

-- exemple
SELECT MAX(id_wod) FROM wodzone.wods w ;
ALTER SEQUENCE wods_id_wod_seq RESTART WITH 295;

--REQUETE pour PUCES => pour extraire la liste des participant avec un id_competition
SELECT
  sub.id_participant, sub.name, sub.id_division, sub.team AS category, sub.planning_date,
  sub.heat_title, sub.heat_debut, sub.line_number, sub.id_wod, sub.min_id_wod_score_details,
  MAX(CASE WHEN sub.rn = 1 THEN sub.first_name || ' ' || sub.last_name END) AS athlete_1,
  MAX(CASE WHEN sub.rn = 2 THEN sub.first_name || ' ' || sub.last_name END) AS athlete_2,
  MAX(CASE WHEN sub.rn = 3 THEN sub.first_name || ' ' || sub.last_name END) AS athlete_3,
  MAX(CASE WHEN sub.rn = 4 THEN sub.first_name || ' ' || sub.last_name END) AS athlete_4
FROM (
  SELECT
    p.id_participant, d.name, d.id_division, team, line_number, planning_date, heat_title,
    heat_debut, INITCAP(a.first_name) AS first_name, UPPER(a.last_name)    AS last_name,
    DENSE_RANK() OVER (PARTITION BY p.id_participant, w.id_wod ORDER BY a.first_name, a.last_name) AS rn,
    w.id_wod,
    MIN(wsd.id_wod_score_details) OVER (PARTITION BY p.id_participant, w.id_wod) AS min_id_wod_score_details
  FROM wodzone.participants p
  JOIN wodzone.athletes            a   ON a.id_participant   = p.id_participant
  JOIN wodzone.participant_divisions pd ON pd.id_participant = p.id_participant
  JOIN wodzone.divisions           d   ON d.id_division      = pd.id_division
  JOIN wodzone.wods                w   ON w.id_division      = d.id_division
  JOIN wodzone.wod_score_details   wsd ON wsd.id_wod         = w.id_wod
  JOIN wodzone.lines               l   ON l.id_participant   = p.id_participant
  JOIN wodzone.heats               h   ON h.id_heat          = l.id_heat
  JOIN wodzone.planning_wods       pw  ON pw.id_planning_wod = h.id_planning_wod
  JOIN wodzone.competitions        c   ON d.id_competition   = c.id_competition
  WHERE c.id_competition = 96 AND is_for_test_mode = false
) sub
GROUP BY
  sub.id_participant, sub.id_division, sub.name, sub.team, sub.planning_date, sub.line_number, sub.heat_title, 
  sub.heat_debut, sub.id_wod, sub.min_id_wod_score_details
ORDER BY sub.name, sub.heat_debut, sub.line_number;



SELECT 
    d.id_division, 
    d.name,
    w.id_wod,
    MIN(wsd.id_wod_score_details) AS min_id_wod_score_details
FROM wodzone.divisions d
JOIN wodzone.wods w ON w.id_division = d.id_division 
JOIN wodzone.wod_score_details wsd ON wsd.id_wod = w.id_wod 
WHERE d.id_competition = 75
GROUP BY d.id_division, d.name, w.id_wod
order by d.name;

-- ------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- ------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- CLI STRIPE ->  stripe listen --forward-to localhost:5001/webhook
-- ------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- ------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- a creer en prod
-- J'ai commenté // transition: all .5s; dans .mainContainer { A voir s'il manque une animation dans l'app

-- TODO Fix button fixlinks leaderboard planning qui ne s'affiche pas par exemple
-- TODO update delete user avec claims 
-- TODO verifier les erreurs upload multer pour les images trop lourdes
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
ALTER TABLE wodzone.goodies_athletes DROP COLUMN tee_shirt;
ALTER TABLE wodzone.goodies_athletes DROP COLUMN short;
ALTER TABLE wodzone.goodies_athletes DROP COLUMN pointure;
ALTER TABLE wodzone.goodies_athletes DROP COLUMN debardeur;
-- ------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- ------------------------------------------------------------------------------------------------------------------------------------------------------------------

INSERT INTO wodzone.topics
(title, link, slug, description, component, tags, suggestion, thematique, subtitles)
VALUES(
    'Créer votre planning',
    '/topics/gestion-compet/59',
    'Marche à suivre • Organisateur',
    'Configurer vos options de planning, Wodzone s''occupe du reste pour générer automatiquement votre planning, vos heats, remplir les lignes de façon optimisée. Et bien plus encore.',
    'HelpTopicGeneral',
    ARRAY['planning', 'heat', 'floor', 'ligne', 'line'],
    'Créer votre planning',
    'gestion-compet',
    ARRAY['titre_1', 'titre_2', 'titre_3']
);

UPDATE wodzone.topics SET subtitles=ARRAY[
'Inscription dans la liste d''attente', ''
] WHERE id_topic=64;
-- ------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- ------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- CREATE INDEX nom_de_index ON nom_de_table (nom_de_colonne);
-- ------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- ------------------------------------------------------------------------------------------------------------------------------------------------------------------


CREATE OR REPLACE PROCEDURE wodzone.delete_competition(idCompetition integer)
LANGUAGE plpgsql
AS $$
DECLARE 
    divisions_ids INTEGER[];
    wods_ids INTEGER[];
    wod_id INTEGER;
    participants_ids INTEGER[];
    participant_id INTEGER;
begin
	SELECT ARRAY(
		SELECT id_wod FROM wodzone.competitions c
		join wodzone.divisions d on c.id_competition = d.id_competition 
		join wodzone.wods w on d.id_division = w.id_division
		WHERE c.id_competition = idCompetition
	) INTO wods_ids;
    -- Loop through the array and call delete_competition function for each ID
    FOREACH wod_id IN ARRAY wods_ids
    LOOP
        CALL wodzone.delete_wod(wod_id);
    END LOOP;
   SELECT ARRAY(
		SELECT id_participant FROM wodzone.competitions c
		join wodzone.divisions d on c.id_competition = d.id_competition 
		join wodzone.participants p on p.id_division = d.id_division
		WHERE c.id_competition = idCompetition
	) INTO participants_ids;
    -- Loop through the array and call delete_competition function for each ID
    FOREACH participant_id IN ARRAY participants_ids
    LOOP
        CALL wodzone.delete_participant(participant_id);
    END LOOP;
  DELETE FROM wodzone.compet_event_modes WHERE id_competition = idCompetition;
  DELETE FROM wodzone.compet_tags WHERE id_competition = idCompetition;
  DELETE FROM wodzone.organisateurs WHERE id_competition = idCompetition;
  DELETE FROM wodzone.divisions WHERE id_competition = idCompetition;
  DELETE FROM wodzone.competitions WHERE id_competition = idCompetition;
END; $$



CREATE OR REPLACE PROCEDURE delete_participant(idParticipant integer)
LANGUAGE plpgsql
AS $$
DECLARE score_ids INTEGER[];
BEGIN
  SELECT ARRAY(SELECT id_score FROM wodzone.scores WHERE id_participant = idParticipant) INTO score_ids;
  delete from wodzone.score_details WHERE id_score = ANY(score_ids);
  delete from wodzone.scores where id_participant = idParticipant;
  delete from wodzone.athletes where id_participant =idParticipant;
  delete from wodzone.participants where id_participant =idParticipant;
END; $$

CALL wodzone.delete_competition(21)


ALTER SEQUENCE wodzone.users_id_seq RESTART WITH 1;



CREATE OR REPLACE PROCEDURE delete_wod(idWod integer)
LANGUAGE plpgsql
AS $$
DECLARE score_ids INTEGER[];
BEGIN
  SELECT ARRAY(SELECT id_score FROM wodzone.scores WHERE id_wod = idWod) INTO score_ids;
  DELETE FROM wodzone.score_details WHERE id_score = ANY(score_ids);

  DELETE FROM wodzone.scores WHERE id_wod = idWod;
  DELETE FROM wodzone.wod_score_details WHERE id_wod = idWod;
  DELETE FROM wodzone.wod_details WHERE id_wod = idWod;
 	DELETE FROM wodzone.wods WHERE id_wod = idWod;
END; $$


CREATE OR REPLACE PROCEDURE delete_PlanningWod(idPlanningWod integer)
LANGUAGE plpgsql
AS $$
DECLARE heat_ids INTEGER[];
BEGIN
  SELECT ARRAY(SELECT id_heat FROM wodzone.heats WHERE id_planning_wod = idPlanningWod) INTO heat_ids;
  DELETE FROM wodzone.lines WHERE id_heat = ANY(heat_ids);

  DELETE FROM wodzone.heats WHERE id_planning_wod = idPlanningWod;
  DELETE FROM wodzone.planning_wods WHERE id_planning_wod = idPlanningWod;
END; $$


CREATE OR REPLACE PROCEDURE delete_floor(idFloor integer)
LANGUAGE plpgsql
AS $$
DECLARE planning_wod_ids INTEGER[];
DECLARE heat_ids INTEGER[];
BEGIN
  SELECT ARRAY(SELECT id_planning_wod FROM wodzone.planning_wods WHERE id_floor = idFloor) INTO planning_wod_ids;
  SELECT ARRAY(SELECT id_heat FROM wodzone.heats WHERE id_planning_wod = ANY(planning_wod_ids)) INTO heat_ids;
  DELETE FROM wodzone.lines WHERE id_heat = ANY(heat_ids);

  DELETE FROM wodzone.heats WHERE id_planning_wod = ANY(planning_wod_ids);
  DELETE FROM wodzone.planning_wods WHERE id_planning_wod = ANY(planning_wod_ids);
  DELETE FROM wodzone.floors WHERE id_floor = idFloor;
END; $$


CREATE OR REPLACE PROCEDURE delete_participant(idParticipant integer)
LANGUAGE plpgsql
AS $$
DECLARE score_ids INTEGER[];
BEGIN
  SELECT ARRAY(SELECT id_score FROM wodzone.scores WHERE id_participant = idParticipant) INTO score_ids;
  delete from wodzone.score_details WHERE id_heat = ANY(score_ids);
  delete from wodzone.scores where id_participant = idParticipant;
  delete from wodzone.athletes where id_participant =idParticipant;
  delete from wodzone.participants where id_participant =idParticipant;
END; $$



-- async function getParticipants (req, res) {
--   try {
--     const { id_competition } = req.params;
--     const results = await pool.query(`
--     SELECT
--       p.id_participant, cpt.id_competition, cpt."name" as compet_name, pdiv.id_division, p.id_club, d."name" as division_name, team,
--       c."name" as club_name, sorting, nb_competitor_by_team, is_for_test_mode,
--       jsonb_agg(DISTINCT jsonb_build_object(
--         COALESCE(wod.id_wod::TEXT, 'noWod'), jsonb_build_object(
--           'primaryScore', primaryscore, 'secondaryScore', secondaryScore, 'thirdScore', thirdScore, 'id_wod', wod.id_wod, 'wodName', wod."name", 'order', wod."order",
--           'id_participant', p.id_participant, 'coef', wod.coef, 'cap', wod.cap, 'wodType',  wt1."name", 'suffix', wt1.suffix, 'suffixSecondary', wt2.suffix, 'suffixThird', 
--           wt3.suffix, 'lot_wod', lot_wod,
--           'primary_compared', wt1.compared, 'secondary_compared', wt2.compared, 'third_compared', wt3.compared, 
--           'spot_limited', wod.spot_limited, 'max_point_to_give', wod.max_point_to_give
--         )
--       )) as scores,
--       jsonb_agg(DISTINCT jsonb_build_object(
--         'id_athlete', id_athlete, 'id_user', id_user, 'firstname', first_name, 'lastname', last_name, 'gender', gender, 'email', email)
--       ) as athletes
--       FROM wodzone.participants p
--       lEFT JOIN wodzone.clubs c on c.id_club = p.id_club 
--       lEFT JOIN wodzone.athletes atl ON atl.id_participant = p.id_participant
--       JOIN wodzone.participant_divisions pdiv ON pdiv.id_participant = p.id_participant
--       JOIN wodzone.divisions d ON d.id_division = pdiv.id_division
--       JOIN wodzone.competitions cpt ON cpt.id_competition = d.id_competition
--       LEFT JOIN wodzone.scores sc ON sc.id_participant = p.id_participant 
--       LEFT JOIN wodzone.wods wod ON wod.id_wod = sc.id_wod 
--       LEFT JOIN wodzone.wod_types wt1 ON wt1.id_wod_type = wod.id_primary_score 
--       LEFT JOIN wodzone.wod_types wt2 ON wt2.id_wod_type = wod.id_secondary_score 
--       LEFT JOIN wodzone.wod_types wt3 ON wt3.id_wod_type = wod.id_third_score
--       WHERE cpt.id_competition = $1
--       GROUP BY p.id_participant, d."name", cpt."name", cpt.id_competition, c."name", sorting, nb_competitor_by_team, pdiv.id_participant_divisions;
--     `, [id_competition]);
--     res.json(results.rows) 
--   } catch (error) {
--     console.log(error)
--   }
-- }